name: CI for the web service

on:
  push:
    paths:
      - 'services/web/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Bootstrap all services
        run: npm run bootstrap
      - name: Run e2e tests
        uses: cypress-io/github-action@v2
        with:
          install: false
          record: true
          start: npm run dev
          wait-on: " http://localhost:3000 "
          working-directory: services/web
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_ENV: test
  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Bootstrap all services
        run: npm run bootstrap
      - name: Deploy the web service
        run: npm run deploy --prefix services/web
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}